[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_identifier = "cheryl-dbins"
db_connection = "aws_rds_conn_id_cheryl"
username = 'postgres'
password = '12341234'
host = 'cheryl-dbins.cvwhaidrmrqj.us-east-2.rds.amazonaws.com'
port = '5432'  # Default port for PostgreSQL
default_db = 'postgres'  # Default database you can connect to
db_name = 'demo_wine'
db_alchemy_driver = "postgresql+psycopg2"

[files]
s3_bucket = "de300spring2024"
s3_key = "cheryl_chen/lab8/wine.csv"  # Using the key from wine_config.toml for consistency
remote_file = "wine.csv"
local_file = "wine.csv" # Specify local file path for MWAA

[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "Wine"  # Use the label that matches your dataset column
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95

